test: self-hosted runner

diff --git a/.github/workflows/bazel.yaml b/.github/workflows/bazel.yaml
--- a/.github/workflows/bazel.yaml
+++ b/.github/workflows/bazel.yaml
@@ -16,8 +16,8 @@ env:
 
 jobs:
   test:
-    # runs-on: runs-on=${{ github.run_id }}/cpu=4/ram=16/family=m6idn/spot=false/image=ubuntu24-full-x64/extras=s3-cache
-    runs-on: ubuntu-latest
+    runs-on: runs-on=${{ github.run_id }}/cpu=4/ram=16/family=m6idn/spot=false/image=ubuntu24-full-x64/extras=s3-cache
+    # runs-on: ubuntu-latest
     steps:
       - name: Enable S3 Cache for Self-Hosted Runners
         # these env vars are set (and exposed) when it is a self-hosted runner with extras=s3-cache
@@ -32,10 +32,11 @@ jobs:
 
       - name: Check bazel
         run: |
-          which bazel
-          whereis bazel
-          echo "$PATH"
-          bazel version
+          ls -la /usr/local/bin/
+          echo "path: $PATH"
+          which bazel || echo "which bazel failed"
+          whereis bazel || echo "whereis bazel failed"
+          bazel version || echo "bazel version failed"
 
       # - uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
       #   with:
